# Generated by Django 3.1.3 on 2022-03-29 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'File'), (2, 'Dir')], default=1, max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('on_delete', models.CharField(choices=[(1, 'Has Deleted'), (0, 'Exists')], default=0, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_dir', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.source')),
            ],
            options={
                'ordering': ('created_at', 'name'),
                'index_together': {('parent_dir_id', 'name')},
            },
        ),
    ]
