# Generated by Django 3.1.3 on 2022-03-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='source',
            index_together={('parent_dir_id', 'name')},
        ),
    ]
