# Generated by Django 3.1.3 on 2022-04-22 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.source')),
            ],
            options={
                'ordering': ('updated_at',),
                'index_together': {('file', 'updated_at')},
            },
        ),
    ]
